### ISSUE TITLE
Couldn't find market cap

### ISSUE THREAD

**Issue by mjpower515** [tomgs/sentdexworkarounds#1]
I appreciate your help with this. after some digging, I was able to find market cap as sharesOutstanding
Price/Sales is priceToSalesTrailing12Months

as for trailing p/e the best i could figure is calculating it using by dividing 'currentPrice' by 'trailingEps'

**Comment by TomGranot** [comment]
@mjpower515 Yeah it's a problem, some of the metrics are just not being pulled at all from Yahoo's servers. 

One by one:

1. **Market Cap** - *sharesOutstanding* is, as far as I can tell ([look at footnote no. 5 to the right](https://finance.yahoo.com/quote/MSFT/key-statistics?p=MSFT)) the **number** of shares outstanding, not the actual market cap. You could, however, calculate the **market cap** by [multiplying the number of shares outstanding by the current stock price](http://www.investopedia.com/ask/answers/122314/what-difference-between-market-capitalization-and-shares-outstanding.asp). Added it now - notice I didn't change the numbering, just added a 35th & 36th elements to `gather`, called `currentPrice` & `sharesOutstanding`, respectively.

2. **Price/Sales** - I'm not sure *Price/Sales* is indeed *priceToSalesTrailing12Months* (in Harrison's specific case). I'll try and repost this in the [PythonProgramming.net forum thread](https://pythonprogramming.net/community/519/Scikit%20Learn%20Machine%20Learning%20Tutorial%20For%20Investing%20-%20Pt.%2022%20-%20Workaround/) and see if we can get an answer.

3. **Trailing P/E** - As per [here](https://www.google.co.il/search?q=investopedis+trailing+p%2Fe&oq=investopedis+trailing+p%2Fe&aqs=chrome..69i57.3657j0j7&sourceid=chrome&ie=UTF-8), it seems that your calculation is indeed correct. Adding it now - same idea as item no. 1 on the list, just with division instead of multiplication.

I'm not on my Linux machine right now where all the JSON files are and I don't want to download all of them from here - If someone could check that this still works after the fixes I'll be grateful. I think there might be problem with the integer multiplication/division because I didn't change the type to Integer, but i'm not sure.

Thanks for writing this down!

**Comment by TheAwkwardAdult** [comment]
@tomgs Can you please help me out? I'm stuck. I copied and pasted the same code, but the dataframe and csv file both are empty with only the columns.What should I do?

**Comment by TomGranot** [comment]
First of all, if you're talking about the **NO_NA** file, then it should be blank - notice my comment in the bottom.

If you're talking about the **WITH_NA** file, then let's try and break your process point by point:

1. Can you access the API link? It might've changed since I wrote it.
2. If you can access the API, look at some of the field names. Have they changed since I wrote this?
3. Can you download the KeyStats in JSON format? Are the folders being filled with JSON files?
4. Are the JSON files full and formatted correctly? 

If all of those are a yes, I'm not really sure how to help you - this generated a full **WITH_NA** file for me.

**Comment by TheAwkwardAdult** [comment]
Well, thanks Tom for your help. I think there was some problems with the
features. But I'm not sure. I just adjusted a few lines and got the csv
file filled but didn't quite understood what the error was. Thanks anyway.
😀😀😀

**Comment by TomGranot** [comment]
Glad I could..... help? :)

**Comment by steviestevepy** [comment]
Hi Tom,
Thanks for your workaround.
I have noticed that in that line of code 

> e = e.replace("MY/PATH/TO/THE/TUTORIAL/FOLDER/_KeyStats","")

 you forgot the > \\

The right one should be e = e.replace("MY/PATH/TO/THE/TUTORIAL/FOLDER/_KeyStats\\","")
so that e (the stock name) is replaced clean. 
I have noticed that without > \\ the thicker to be searched comes our i.e "/aapl" which will not be found by the api.
just in case future users get stuck 
Thanks again.

**Comment by TomGranot** [comment]
Oh, sounds reasonable. Changing it now.

**Comment by steviestevepy** [comment]
my apologies Tom. The  > \ should be double, otherwise a single one would just be read as an escape command.
Thanks.

**Comment by TomGranot** [comment]
Hehe you're quite alright. I haven't touched this in a bit - should've caught it myself.
Thanks!

**Comment by kartikk2** [comment]
Hey, can you post the code which is perfectly working? I am getting an empty csv files with only the column names.

**Comment by TomGranot** [comment]
I actually don't have that code anymore, this is an old repo. Sorry:(
