### ISSUE TITLE
22.py

### ISSUE THREAD

**Issue by GrugLife** [tomgs/sentdexworkarounds#2]
Thank you for this updated code.  One issue I found on 22.py is that an N/A on the Yahoo finance key statistics website will be represented as a blank field in the json file.  For example, ABBV has N/A for free cash flow, which is shown in the json file as "freeCashflow":{}.  When downloading the dataframe to a csv file in teh code, the code defaults this to the next number it finds.  In this case, freeCashflow would get populated with earningsGrowth, "freeCashflow":{},"operatingCashflow":{},"earningsGrowth":{"raw":0.278,"fmt":"27.80%"}.  Any idea on how to fix this?  I am struggling to figure it out.

**Comment by TomGranot** [comment]
Thanks for opening this issue!

I think that's a regex issue - this is the code that's actually searching inside the JSON:
`regex = re.escape(each_data) + r'.*?"(\d{1,8}\.\d{1,8}M?B?K?|N/A)%?'`

Notice that it accounts for 2 options in the JSON output:

1. A floating-point number (which it later interprets into a percentage to show figures like 23.6% / attaches B/M/K in order to show figures like 13.4B or 56.4K).
2. An N/A.

In the case of *nothing*, which is what you're referring to (I think), the regex does just go to the next value (jumps over *freeCashFlow* into *operatingCashFlow*), and tries to find a number or an N/A.

I think a solution might involve looking for a blank space inside the regex itself, then using the same script I use for the exception (the one that adds N/A when the regex fails) in order to insert an N/A into the script.

Feel free to submit a fix - I'll accept it. This workaround is anything but complete - it only allows you to move forward with the tutorial. I'll appreciate any help I can get with it. Plus, it's a nice exercise to try and fix stuff in the tutorials you do - makes you really think.

Again - thank you for the issue!
